### ISSUE TITLE
Installation procedure is incorrect and incomplete

### ISSUE THREAD

**Issue by SalvatorePollaci** [ezsystems/ezplatform-drawio-fieldtype#2]
Hi,
the installation procedure found here https://github.com/ezsystems/ezplatform-drawio-fieldtype/blob/master/docs/INSTALL.md is incorrect and incomplete.

This is the procedure I followed to get this field type working:

**1)Get the bundle using composer**
composer require ezsystems/ezplatform-drawio-fieldtype:dev-master

**2)Enable the bundle**
```
// app/AppKernel.php
public function registerBundles()
{
    $bundles = array(
        // ...
        new EzSystems\EzPlatformDrawIOFieldTypeBundle\EzPlatformDrawIOFieldTypeBundle(),
        // ...
    );
}
```

**3)Assets Install**
```
bin/console assets:install
```

**4)Assetic Dump**
```
bin/console assetic:dump web
```

**5)Clear Cache**
```
bin/console cache:clear
```

**6)Create missing service**
As stated here(https://github.com/ezsystems/ezplatform-drawio-fieldtype/issues/1), an eZ Platform field type needs to have defined an indexable class.

```
ezpublish.fieldtype.indexable.ezdrawio:
        class: "%ezpublish.fieldType.indexable.unindexed.class%"
        tags:
            - {name: ezpublish.fieldType.indexable, alias: ezdrawio}
```

**7)Create new Content Class(eg: Diagram) with attribute Draw IO Field Type**
